# Uncomment the next line to define a global platform for your project
 platform :ios, '11.3'

target 'home' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Quickblox-WebRTC'
  pod 'QuickBlox'
  pod 'SVProgressHUD'
  pod 'SwiftLint'

end
